library(shiny)
library(htmltools)
library(purrr)
library(officer)
library(flextable)
library(stringr)
library(magrittr)
library(tidyr)
library(dplyr)
library(tippy)
library(RDCOMClient)
library(tabulapdf)
library(rlang)
library(shiny.i18n)
library(tidystringdist)
library(gt)

source("tidy_label.R")
source("tidy_tax.R")
source("tagsTextInput.R")
source("format_baaksai.R")
source("tidyup2.R")
# source("validate_label.R")

translator <- Translator$new(translation_json_path = "translations.json")
translator$set_translation_language("zh")
