library(shiny)
library(htmltools)
library(purrr)
library(officer)
library(flextable)
library(stringr)
library(magrittr)
library(tidyr)
library(dplyr)
library(tippy)
library(RDCOMClient)
library(tabulizer)
library(rlang)
# library(SWinTypeLibs)
source("tidy_label.R")
source("tidy_tax.R")
source("tagsTextInput.R")
source("format_baaksai.R")
source("tidyup2.R")
# Move DescTool Package into app/library